### ISSUE TITLE
Checklist for 1.0

### ISSUE THREAD

**Issue by Obbut** [owowagency/swiftui-router#4]
- [x] Proper dismissal support for presented sheets
- [x] Fix all remaining [`#warning`](https://github.com/owowagency/swiftui-router/search?q=%23warning)s
- [x] Remove [`func unimplemented()`](https://github.com/owowagency/swiftui-router/blob/master/Sources/Router/Misc/unimplemented.swift)
- [ ] Update / check readme
- [ ] Revisit public API enums, and if they can stay stable or should be replaced by something else, especially `RoutePresentationMode`

Optional:
- [ ] A small demo app, either in or outside the repository
- [x] Very basic macOS support
